### PR TITLE
use data from chrome devtools trace

### PR DESCRIPTION
**Pull request by andersy005**
@maxrjones / @katamartin, 

this is my first attempt at using data (e.g. request timings, etc) from chrome devtools trace. The data from the produced JSON is quite complex, and i'm still trying to figure out how to access the frame durations information from this JSON.

### CODE REVIEW

**Comment by andersy005** [comment]
after a few unsuccessful attempts to retrieve the request data from the trace, i noticed inconsistencies between the request data recorded in the trace and our previous measurements. i found this puzzling and i really couldn't make sense of it. instead of letting this PR become stale, i'm closing it for now. If needed, I can reopen it later.

**Comment by andersy005** [comment]
i'm going to open a separate PR to capture the trace (JSON) data and persist them locally. This data can then be loaded into chrome devtools for visualization purposes.

**Comment by maxrjones** [comment]
> after a few unsuccessful attempts to retrieve the request data from the trace, i noticed inconsistencies between the request data recorded in the trace and our previous measurements. i found this puzzling and i really couldn't make sense of it. instead of letting this PR become stale, i'm closing it for now. If needed, I can reopen it later.

Do you mind sharing more about the inconsistencies? Yesterday I looked into the unexpected lag between requests finishing along with the unexpected order of requests starting (e.g., chunks being requested before .zmetadata) and determined that it related to a misunderstanding about the requests data in the Playwright output. I interpreted `request_start` as the time relative to the beginning of the test, whereas from https://playwright.dev/docs/api/class-request#request-timing-return it is actually “Time immediately before the browser starts requesting the resource  from the server, cache, or local resource. The value is given in milliseconds relative to `startTime`, where `startTime` is "Request start time in milliseconds elapsed since January 1, 1970 00:00:00 UTC". A new example from playwright is below, and I found the general structure to be similar to the requests recorded from the chromium trace. 

Untitled

**Comment by maxrjones** [comment]
> i'm going to open a separate PR to capture the trace (JSON) data and persist them locally. This data can then be loaded into chrome devtools for visualization purposes.

Are you planning to use the approach of `browser.start_tracing(path='trace.json')` from https://github.com/carbonplan/benchmark-maps/pull/13/files or something else? I found that the result from that PR could be opened in chromium's trace viewer (`chrome://tracing/`) but wasn't able to inspect the results using the richer visualization set in chrome devtools.

**Comment by andersy005** [comment]
for example, here are some sample entries that i got from `trace.json`:

```json

{
        "method": "GET",
        "request_start": 77063118429,
        "response_end": 77063212576,
        "total_response_time_in_ms": 1219.181,
        "url": "https://carbonplan-maps.s3.us-west-2.amazonaws.com/v2/demo/4d/tavg-prec-month/2/climate/0.0.1.2"
      },
      {
        "method": "GET",
        "request_start": 77063118795,
        "response_end": 77063345247,
        "total_response_time_in_ms": 1039.72,
        "url": "https://carbonplan-maps.s3.us-west-2.amazonaws.com/v2/demo/4d/tavg-prec-month/2/climate/0.0.1.3"
      },
 {
        "method": "GET",
        "request_start": 77062653453,
        "response_end": 77062859645,
        "total_response_time_in_ms": 246.431,
        "url": "https://carbonplan-maps.s3.us-west-2.amazonaws.com/v2/demo/4d/tavg-prec-month/.zmetadata"
      },
```

when these data are compared to the existing data, i was noticing that the units for response_start, response_end seem to be way off, and the total_response_time_in_ms measurements were relatively higher

```json
 {
        "method": "GET",
        "request_start": 173.748,
        "response_end": 289.187,
        "total_response_time_in_ms": 115.43900000000002,
        "url": "https://carbonplan-maps.s3.us-west-2.amazonaws.com/v2/demo/4d/tavg-prec-month/.zmetadata"
      },
      {
        "method": "GET",
        "request_start": 255.3,
        "response_end": 306.623,
        "total_response_time_in_ms": 51.32299999999998,
        "url": "https://carbonplan-maps.s3.us-west-2.amazonaws.com/v2/demo/4d/tavg-prec-month/0/month/0"
      },
      {
        "method": "GET",
        "request_start": 267.656,
        "response_end": 324.783,
        "total_response_time_in_ms": 57.12700000000001,
        "url": "https://carbonplan-maps.s3.us-west-2.amazonaws.com/v2/demo/4d/tavg-prec-month/0/band/0"
      },
  ```

**Comment by maxrjones** [comment]
thanks for sharing @andersy005!
> the units for response_start, response_end seem to be way off

this is consistent with the response_start, response_end being relative to startTime for playwright but absolute from chromium tracing.

> total_response_time_in_ms measurements were relatively higher

this is interesting and could reflect the specific metrics we've chosen to include from https://playwright.dev/docs/api/class-request#request-timing-return. for example, if chromium's record includes the time necessary to secure a connection but the metrics we're extracting from playwright does not. IMO it's worthwhile to record both from the same run to see how different they are for the exact same requests. would it duplicate your efforts for me to test that out and share a plot of the results?

**Comment by maxrjones** [comment]
@andersy005 I think the differences in the total_response_time_in_ms correspond to differences in when the timer starts. `response_end` from playwright is actually quite similar to the `total_response_time_in_ms` from the chromium trace, indicating that by subtracting `request_start` in playwrightwe are measuring a subset of the time that's recording in the chromium trace:
image

**Comment by andersy005** [comment]
>  I found that the result from that PR could be opened in chromium's trace viewer (chrome://tracing/) but wasn't able to inspect the results using the richer visualization set in chrome devtools.

here's how i load the JSON into chrome dev tools: 


https://github.com/carbonplan/benchmark-maps/assets/13301940/fc6bc0ab-c200-46b3-b638-d7a31bae8563

**Comment by maxrjones** [comment]
> here's how i load the JSON into chrome dev tools

thanks! did you record the JSON programmatically? I get "Recording failed; no frames found in trace data"

**Comment by andersy005** [comment]
> thanks! did you record the JSON programmatically? I get "Recording failed; no frames found in trace data"

of course! try running the benchmarks using this PR: 

- https://github.com/carbonplan/benchmark-maps/pull/16 


there should be two new directories: `chrome-devtools-traces` and `playwright-screenshots`. These directories are not checked into git though

```bash
❯ tree                                                                                                                                           ─╯
.
├── LICENSE
├── README.md
├── binder
│   ├── Dockerfile
│   ├── apt.txt
│   └── environment.yml
├── chrome-devtools-traces
│   ├── 2023-07-12T16-59-19-1.json
│   └── 2023-07-12T17-00-34-1.json
├── data
│   ├── data-2023-06-21T16-28-43.json
│   ├── data-2023-06-21T17-37-37.json
│   └── data-2023-06-22T16-22-08.json
├── main.py
├── playwright-screenshots
│   ├── 2023-07-12T16-59-19-1.png
│   └── 2023-07-12T17-00-34-1.png
└── pyproject.toml
```

**Comment by andersy005** [comment]
> Do you mind sharing more about the inconsistencies? Yesterday I looked into the unexpected lag between requests finishing along with the unexpected order of requests starting (e.g., chunks being requested before .zmetadata) and determined that it related to a misunderstanding about the requests data in the Playwright output. I interpreted request_start as the time relative to the beginning of the test, whereas from [playwright.dev/docs/api/class-request#request-timing-return](https://playwright.dev/docs/api/class-request#request-timing-return) it is actually “Time immediately before the browser starts requesting the resource from the server, cache, or local resource. The value is given in milliseconds relative to startTime, where startTime is "Request start time in milliseconds elapsed since January 1, 1970 00:00:00 UTC". A new example from playwright is below, and I found the general structure to be similar to the requests recorded from the chromium trace.

this explanation has helped me understand the situation better and has corrected my misconceptions about the results i was obtaining. i appreciate your help in clearing this up

**Comment by andersy005** [comment]
>  IMO it's worthwhile to record both from the same run to see how different they are for the exact same requests. 

👍🏽. i will make to include these in #16

**Pull request closed without merging**
